Added images for rooms#7
HackYourFuture-CPH/chattie pull request #158
Opened 2020-09-24 11:54 UTC by Aswini-D3

# Description
We can see the images of the rooms here...so that we can have a visual representation of the room.

Fix #7 
npm run storybook

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-09-24 18:51 UTC, tpetrina commented on src/client/components/CreateANewRoomButton/CreateANewRoomButton.js
> -
Why did you remove this empty line?

2020-09-24 18:51 UTC, tpetrina commented on src/client/components/RoomList/RoomList.css
> +img {
Do not style _all_ images in the app, have a better CSS selector only for this component.

2020-09-27 11:25 UTC, bytewiz requested changes

2020-09-29 11:11 UTC, benna100 approved these changes
You are still adding lots of small changes to the PR (line breaks, importing things other places, etc). Please avoid that for another time!

2020-09-29 11:11 UTC, merged

2020-09-29 11:19 UTC, Aswini-D3 commented
> You are still adding lots of small changes to the PR (line breaks, importing things other places, etc). Please avoid that for another time!

Thank you Benjamin..I wont repeat those next time.