Delete Notification at end point
HackYourFuture-CPH/chattie pull request #159
Opened 2020-09-24 17:39 UTC by tariqjavid

# Description

 Delete Notification at end point :storyNo:#142

Fixes # (issue)

# How to test? postman

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2020-09-27 08:22 UTC, tpetrina approved these changes
Small nitpicks, fix and then it's good to merge!

2020-09-27 08:22 UTC, tpetrina commented on src/server/api/controllers/notifications-controller.js
> +// users delete by id
Missing a blank line before the comment.

2020-09-27 08:22 UTC, tpetrina commented on src/server/api/controllers/notifications-controller.js
> +const deleteNotification = async (notiId) => {
Rename to `notificationId`

2020-09-27 08:22 UTC, tpetrina commented on src/server/api/routes/notifications-router.js
> +/**
Missing empty line before comment.

2020-09-27 08:22 UTC, tpetrina commented on src/server/api/routes/notifications-router.js
> + * /Notification/{ID}:
Prefer lowercase `notification` in URLs.

2020-09-27 08:22 UTC, tpetrina commented on src/server/api/routes/notifications-router.js
> +
Remove the empty line between comment and a method.

2020-09-27 10:57 UTC, bytewiz requested changes
See comments above

2020-09-28 14:38 UTC, benna100 approved these changes
Looks good

2020-09-28 14:38 UTC, merged