Channel messages view
HackYourFuture-CPH/chattie pull request #175
Opened 2020-09-29 10:01 UTC by yukafjaponesa

# Description

Please provide a short summary explaining what this PR is about.

Fixes #41 

# How to test?
use http://localhost:3000/channel/2 to see the messages fetched.

# Checklist

- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-09-29 11:25 UTC, benna100 reviewed
What is this story for?

2020-10-01 11:32 UTC, benna100 requested changes
Looks pretty good, small change and then its ready :)

2020-10-01 11:32 UTC, benna100 commented on src/client/containers/Channel/Channel.js
> +    </ul>
Please use the `ChannelMessagesView` here remember to import it
```suggestion
    <ChannelMessagesView messages={messages} />
```

2020-10-01 16:18 UTC, tpetrina commented on src/client/containers/ChannelMessagesView/ChannelMessagesView.js
> +    <ul className="container">
If you are not styling it, then just rename the class name to `channel-messages`. The class name `container` is a bit too generic.

2020-10-01 16:19 UTC, tpetrina reviewed
Please rename class name and address Benjamin's comment.

2020-10-02 12:16 UTC, closed without merging