getting last message of recent channels-backend
HackYourFuture-CPH/chattie pull request #185
Opened 2020-09-30 12:34 UTC by afrouzhakim

# Description
get the last message and the title of the channels, from the recent channels for a specific user that defined in the endpoint. 

Fixes #4 

# How to test?
run "npm run server" and go to "http://localhost:5000/api/channels-message/2"

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-09-30 15:26 UTC, benna100 requested changes
Hey Afrouz...

As far as i can see, then what you are doing here can be done in the frontend. If you want message for a specific user just use `/api/messages?sender=3` With the messages you can figure out what channels they belong to and theeby render the recent messages (or am i missing somthing here?)

The story was a frontend task that changes the UserList to recentMessages. I can see that you have spent a long time on this, and its actually pretty impressive, so really good job on getting this to work. But if you had asked about this task or communicated a little, you could have save probably a weeks development. And all this code we dont really need cause the api already supports it. And that sucks that you have made all this (super impressive work) that we dont get to use.

2020-10-01 09:26 UTC, afrouzhakim commented
Hi Benjamin, 
thank you for your feedback. Yes you are right I must to have a better overview of my classmates work before start coding! I will try to use the API that you mentioned and complete my task on that.

2020-10-01 16:26 UTC, tpetrina approved these changes
Great job! Please remove a couple of files and lines and that's basically it!.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/controllers/channels-message-controller.js
> +    console.log(userId);
Remove console log from here.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/controllers/channels-message-controller.js
> +    console.log(channels);
Remove console.log and leave an empty line here.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/controllers/channels-message-controller.js
> +      throw new Error(`create your first conversation!`);
Don't throw, return `[]` instead.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/routes/channels-message-router.js
> +router.get('/:userId', (req, res, next) => {
Missing Swagger docs.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/controllers/channels-message-controller.js
> +          .orderBy('channel_messages.updated_at', 'asc')
I think you should use `desc` right? Get the latest message so `desc`.

2020-10-01 16:26 UTC, tpetrina commented on src/server/api/controllers/channels-message-controller.js
> +// select fk_channel_id from channel_members where fk_user_id=userId;
Please remove it.

2020-10-04 12:14 UTC, benna100 approved these changes

2020-10-04 13:37 UTC, merged