Add poople in room
HackYourFuture-CPH/chattie pull request #232
Opened 2020-10-05 18:28 UTC by tariqjavid

# Description

Add people in room 

# How to test? import AddPeopleToRoom.js in App.js

Please provide a short summary how your changes can be tested?

# Checklist

- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2020-10-06 07:24 UTC, benna100 requested changes
This is pretty advanced stuff you are doing here Tariq. 

So first of this PR is way too big. Its hard for me to get an overview of what you are actually doing. Therefore it is hard for me to review this PR. Im not sure what is actually happening. 

I have given you some comments. There is no reason to change the PR size or split it up now. Its just for you to know for the next pr

2020-10-06 07:24 UTC, benna100 commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +      <div className="inputsearch">
```suggestion
      <div className="input-search">
```

2020-10-06 07:24 UTC, benna100 commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +        <input type="text" placeholder="Search" onChange={onChangeInput} />
```suggestion
        <input type="text" placeholder="Search for users" onChange={onChangeInput} />
```

2020-10-06 07:24 UTC, benna100 commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +      <div className="add-people">{displayUserInGroup()}</div>
Why is this lower case and the other uppercase? 

All functions are lower case. This looks a little weird. Why are you calling a function here? Why not just have a component?
`<DisplayUserInGroup />`

2020-10-06 07:24 UTC, benna100 commented on src/client/components/AddPeopleToRoom/ChatGroup.js
> +        </div>
**Always** when you are rendering a list of something use ul and li.

2020-10-06 07:24 UTC, benna100 commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const addUserInGroup = (e, id) => {
Good variable naming. what is e

2020-10-06 07:28 UTC, benna100 requested changes

2020-10-06 07:28 UTC, benna100 commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +    setUsers(getUser);
This looks weird. setUsers with getUser. Is getUser not a function? Variable naming really matter here

2020-10-06 07:28 UTC, benna100 commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const search = () => {
Would make sense that this function takes the input it is searching for

2020-10-06 07:28 UTC, benna100 commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const DiplayListOFUsers = () => {
This should definitely be a component

```suggestion
  const diplayListOFUsers = () => {
```

2020-10-06 07:28 UTC, benna100 commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const displayUserInGroup = () => {
This should also be a component

2020-10-06 13:25 UTC, tpetrina commented on src/client/components/AddNewRoom/AddNewRoomStyle.css
> +* {
Do not add this global style here. We have `index.css` in the client folder for global styles.

2020-10-06 13:26 UTC, tpetrina commented on src/client/components/AddNewRoom/RoomForm.js
> +  // if (!roomId) {
Remove this line and leave blank line.

2020-10-06 13:43 UTC, tpetrina reviewed
First of all, great job with such a huge project! Most of my comments are related to naming and other smaller comments. While it may seem superficial, consistency is really important in a big project.
Looking forward to cleaning this up!

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddNewRoom/RoomForm.js
> +  inputChange: PropTypes.func.isRequired,
For consistency, name it `onRoomNameChange` since it is tied to the `roomName` prop.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddNewRoom/RoomForm.js
> +  displaypeopleInGroup: PropTypes.func.isRequired,
Rename to `renderGroup` since it is rendering JSX.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddNewRoom/RoomForm.js
> +  backToAddPeople: PropTypes.func.isRequired,
We prefix functions with `on` so I suggest `onBackToAddPeople`

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoom.css
> +* {
As mentioned before, do not add global styles in component specific css.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoom.stories.js
> +import AddPeopleToRoom from '../../containers/AddPeopleToRoom/AddPeopleToRoom';
We don't usually put containers in storybook - it is intended to showcase components.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  DiplayListOFUsers: PropTypes.func.isRequired,
Functions that render should indicate it in the name. Suggested name `renderUsers`

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  displayUserInGroup: PropTypes.func.isRequired,
Suggested name is `renderUserInGroup`

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  users: PropTypes.objectOf.isRequired,
Not an `objectof` but an `array`

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  addUsers: PropTypes.objectOf.isRequired,
This is an array so the name should be `addedUsers` and the prop type should be `array`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  onChangeInput: PropTypes.func.isRequired,
Suggested name `onChangeSearch`. By the way, you don't send the value itself (should be named `search`). Is this working as intended?

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/AddPeopleToRoomForm.js
> +  nextToGroup: PropTypes.func.isRequired,
The suggested new name `onNext`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/components/AddPeopleToRoom/ChatGroup.js
> +    fetch(url)
Please use `fetchWithAuth`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +const AddNewRoom = ({ addUsers }) => {
The suggested name is `addedUsers`. `addUsers` reads more like `add users` which is a command, not an array.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +    const response = await fetch('api/channels', {
Please use `fetchWithAuth`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +  } //  end  if statement
No need for this comment.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +  if (roomId !== '') {
Usually, we simplify this to either `if (roomId)` or `if (!!roomId)`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +      fetch('api/channel-members', {
Please use `fetchWithAuth`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddNewRoom/AddNewRoom.js
> +  addUsers: PropTypes.objectOf.isRequired,
This is an array, not an object.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  useEffect(() => {
You can use `useQuery` here to simplify a lot of the code. Otherwise, use `fetchWithAuth`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const addUserInGroup = (e, id) => {
No need to even pass `e` here, just pass `id`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +    users.forEach((user) => {
This is a bit too complicated, it can be simplified. But if you don't have time, ignore this comment.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  }; //  end of addUserInGroup function
No need for this comment.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +    const getUser = addUsers.filter((user) => user.id !== id);
If you are filtering `addUsers` which is an array, you are getting a new array. The naming matters so `getUser` looks like a function, use a pluralized noun like `filteredUsers`.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  }; //  end of Remove FromGroup function
Remove comment.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +            key={user.id + 2}
You don't need `key` here.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +            alt={user.id + 2}
`alt` is used for screen readers for blind people, it shouldn't be a number. Write a human-readable text .

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +          <div key={user.id + 3}>{user.user_name}</div>
No need for `key` here.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +            key={user.id + 4}
No need for `key` here.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +            +
Maybe there is a cool icon in the fortawesome library. Check it out.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +            X
Maybe there is a cool icon in the fortawesome library. Check it out.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +  const [toAddRoom, setToAddRoom] = useState('false'); //  thi is use to move to next page
Do not use `'true'` and `'false'` which are strings, use `true` and `false` which are booleans.

2020-10-06 13:43 UTC, tpetrina commented on src/client/containers/AddPeopleToRoom/AddPeopleToRoom.js
> +      {toAddRoom === 'true' ? (
If you use booleans, then you can simplify this to `toAddRoom ? (`

2020-10-07 08:41 UTC, benna100 commented
Well done on the quick changes! There is a warning you need to fix

2020-10-07 12:22 UTC, benna100 commented on src/client/components/AddPeopleToRoom/ChatGroup.js
> +    fetch(url)
There is a comment here tariq

2020-10-08 11:03 UTC, merged