Feature/#289/styling profile
HackYourFuture-CPH/chattie pull request #302
Opened 2020-10-14 11:45 UTC by LucyChyzhova

# Description

Fixed profile page (styling)

Fixes #289 

# How to test?

by npm run dev
![image](https://user-images.githubusercontent.com/50618208/95984157-0fffd200-0e23-11eb-94dd-883c5d9e1047.png)
![image](https://user-images.githubusercontent.com/50618208/95984226-29088300-0e23-11eb-9c93-588e969193c1.png)
![image](https://user-images.githubusercontent.com/50618208/95984317-4a696f00-0e23-11eb-93dd-2f2ffb3b54a4.png)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2020-10-15 06:48 UTC, tpetrina requested changes
Reduce font size: ![image](https://user-images.githubusercontent.com/1407815/96086851-35dcb380-0ec3-11eb-849f-551cb120ee1e.png)

2020-10-18 11:12 UTC, tpetrina approved these changes

2020-10-18 11:12 UTC, tpetrina commented on src/client/components/Profile/Profile.styling.css
>  }
`margin-bottom: 200px`

2020-10-18 11:13 UTC, benna100 approved these changes

2020-10-18 11:13 UTC, merged