created POST api/channel-members
HackYourFuture-CPH/chattie pull request #72
Opened 2020-09-10 21:15 UTC by fzscodes

# Description

POST api for creating new channel members. Task #35 

Fixes # (issue)

# How to test?

api can be tested using postman. Send a POST request to endpoint with user and channel Ids:

POST /api/channel_members HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "userId": 3,
    "channelId": 2
}

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-09-12 15:42 UTC, tpetrina requested changes
Good, but please remove extra code. Also, coordinate with other developers.

2020-09-12 15:42 UTC, tpetrina commented on src/server/api/routes/api-router.js
> +router.use('/channel_members', channelMembersController);
Why is this route `channel_members` when the title of the task is `channel-members`?

2020-09-12 15:42 UTC, tpetrina commented on src/server/api/controllers/channel_members.controller.js
> +  getChannelMembers,
This ticket only required you to add POST, not other methods. They might either be completely unnecessary or they might be covered by other tickets/implementators. Please remove extras.

2020-09-13 08:39 UTC, tpetrina commented on src/server/api/routes/channel-members.router.js
> + *    summary: Create a module
This comment mentions a module, but it is obviously a channel member.

2020-09-13 10:19 UTC, tpetrina commented on src/server/api/routes/channel-members.router.js
> + *        description: The module to create.
You left one more `module` here.

2020-09-13 12:24 UTC, bytewiz requested changes
Minor comments, looks good 👍

2020-09-13 12:24 UTC, bytewiz commented on src/server/api/routes/channel-members.router.js
> +      console.log(error);
Remove the `console.log`, it is just for debugging 👍

2020-09-13 12:24 UTC, bytewiz commented on src/server/api/routes/channel-members.router.js
> + */
Would be nice to add response type for `400` 👍

2020-09-14 11:35 UTC, benna100 approved these changes

2020-09-14 11:36 UTC, merged