Endpoint delete api/messages
HackYourFuture-CPH/chattie pull request #77
Opened 2020-09-11 18:08 UTC by STEP0HEN

# Description

Please provide a short summary explaining what this PR is about.

added the Endpoint: DELETE api/messages.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2020-09-12 16:01 UTC, tpetrina commented on src/server/api/controllers/messages-controller.js
> +  await knex('channel_messages').insert({
You were only supposed to add the `delete` part.

2020-09-12 16:02 UTC, tpetrina requested changes
This PR has a bunch of file changes that shouldn't be here. Please contact me to resolve this issue.

2020-09-13 08:39 UTC, tpetrina commented
I would remove changes to `package.json` and `package-lock.json` as well as the changes to the create method. Then the PR is complete.

2020-09-16 12:47 UTC, benna100 approved these changes

2020-09-16 12:47 UTC, merged