POST/API EndUser corrected one
HackYourFuture-CPH/chattie pull request #80
Opened 2020-09-12 10:24 UTC by CharlesKimMaina

# Description

Please provide a short summary explaining what this PR is about.
POST/API Enduser. 
Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2020-09-12 15:51 UTC, tpetrina commented
Please link to the issue and properly name the PR.

2020-09-12 15:52 UTC, tpetrina requested changes
Looks good, but you did more than you were asked for.

2020-09-12 15:52 UTC, tpetrina commented on src/server/api/controllers/users.controller.js
> +const getUsers = async () => {
Please only add what you were supposed to add. #29 is supposed to cover this.

2020-09-12 15:52 UTC, tpetrina commented on src/server/api/routes/users.router.js
> +router.get('/', (req, res, next) => {
Please remove both GET methods

2020-09-15 14:44 UTC, tpetrina commented on src/server/api/controllers/users.controller.js
> +  return {
No need to return these properties. Especially since you sent them from the UI. You only need to return the id that is generated.

2020-09-15 14:44 UTC, tpetrina commented on src/server/api/controllers/users.controller.js
> +/* const createUser = async (body) => {
Don't commit commented code, it makes too much noise.

2020-09-15 14:45 UTC, tpetrina requested changes
Still small changes that need to be done.

2020-09-15 14:45 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *    summary: Create a module
Is this intentional? Feels like a regression after pasting.

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            - last_seen
Remove `last_seen`

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *              format: date-time
Remove `last_seen`

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            - user_name
```suggestion
 *            - userName
```

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            - profile_image
```suggestion
 *            - profileImage
```

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            user_name:
```suggestion
 *            userName:
```

2020-09-16 13:31 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            last_seen:
```suggestion
 *            profileImage:
```

2020-09-16 13:32 UTC, tpetrina commented on src/server/api/routes/users.router.js
> + *            profile_image:
```suggestion
 *            profileImage:
```

2020-09-17 07:06 UTC, benna100 requested changes

2020-09-17 07:06 UTC, benna100 commented on src/server/api/routes/api-router.js
> +>>>>>>> develop
**Never ever** commit a merge conflict. This is absolutely a no go!

Watch this: https://www.youtube.com/watch?v=JtIX3HJKwfo

Remember your code does not run now. So it shows that you have not even bothered to run your code before making the pr.

2020-09-17 08:48 UTC, benna100 approved these changes

2020-09-17 08:49 UTC, merged