added endpoint DELETE api/channel-members/id
HackYourFuture-CPH/chattie pull request #82
Opened 2020-09-12 19:14 UTC by STEP0HEN

# Description

Please provide a short summary explaining what this PR is about.
This is the PR for deleting channel members

Fixes # (issue)
fixes issue 33
# How to test?

You can test it in postman with **`localhost:5000/api/channel-members/2`** where 2 is the channel member id, could be any id number as long as it exists in your DB.

Please provide a short summary how your changes can be tested?

# Checklist

- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2020-09-13 11:45 UTC, bytewiz requested changes

2020-09-13 11:45 UTC, bytewiz commented on src/server/api/routes/channel-members.router.js
> +      // If result is equal to 0, then that means the channel member id does not exist
Good comment 👍

2020-09-13 11:45 UTC, bytewiz commented on src/server/api/routes/channel-members.router.js
> + */
Would be nice to add the `404` type response here as well 👍  (when the id provided doesn't exist)

2020-09-17 10:48 UTC, benna100 commented
There are merge conflicts here

2020-09-17 20:55 UTC, benna100 approved these changes

2020-09-17 20:55 UTC, merged